--[[
    Script by Tobias00723                          ████████
    from the TGFB server                      ████████  ████████
    Discord : https://discord.gg/hEHd4A3czx ██████          ██████
    any questions?                   ^^   ████     ▒      ▒     █████
    find me on my discord server     ^^ ████      ▒▒      ▒▒▒      ███
    _________________________________ ████       ▒▒▒      ▒▒▒       ███
                                      ███       ▒▒▒▒      ▒▒▒▒       ███
                                     ██       ▒▒▒▒        ▒▒▒▒▒      ███
                                    ███      ▒▒▒▒▒▒        ▒▒▒▒▒▒      ███
        Script as is.               ███     ▓▒▒▒▒▒▒        ▒▒▒▒▒▒▒     ███
                                    ███    ▒▒▒▒▒▒▒▒        ▓▒▒▒▒▒▒▓    ███
        Enjoy The open sauce!       ███   ▓▒▒▓▒▒▓▒▓         ▒▒▓▒▒▒▒▒   ███
                                    ███  ▓▒▓▓▒▓▓▒▓          ▓▓▒▓▓▓▓▓▓  ███
   If used credit, is appreaciated.  █  ▓▓▓▒▓ ▓▓▓▒          ▓▓▓▓ ▒▓▒▓▓  █
        Happy "borrowing" :)           ▓▓▓▓    ▓▓▓   ████    ▓▓▓   ▓▓▓▓
    _________________________________ ▓▓▓      ▓▓    ▓▓▓▓    ▓▓      ▓▓▓
                                     ▓▓        ▓▓    ▓▓▓▓    ▓▓        ▓▓
                                    ▓▓          ▓    ▓▓▓▓     ▓         ▓▓
    Copyright (c) 2025 TGFB                          ▓▓▓▓
    All rights reserved.                             ▓▓▓▓
]]

do
    ---@meta

    --classes
    do

    end
    --The country enumerator contains the constant countryIds and strings for each country present in DCS World. Country ids are indexed starting at 0.
    --https://wiki.hoggitworld.com/view/DCS_enum_country
    country = {
        RUSSIA = 0,
        UKRAINE = 1,
        USA = 2,
        TURKEY = 3,
        UK = 4,
        FRANCE = 5,
        GERMANY = 6,
        AGGRESSORS = 7,
        CANADA = 8,
        SPAIN = 9,
        THE_NETHERLANDS = 10,
        BELGIUM = 11,
        NORWAY = 12,
        DENMARK = 13,
        ISRAEL = 15,
        GEORGIA = 16,
        INSURGENTS = 17,
        ABKHAZIA = 18,
        SOUTH_OSETIA = 19,
        ITALY = 20,
        AUSTRALIA = 21,
        SWITZERLAND = 22,
        AUSTRIA = 23,
        BELARUS = 24,
        BULGARIA = 25,
        CHEZH_REPUBLIC = 26,
        CHINA = 27,
        CROATIA = 28,
        EGYPT = 29,
        FINLAND = 30,
        GREECE = 31,
        HUNGARY = 32,
        INDIA = 33,
        IRAN = 34,
        IRAQ = 35,
        JAPAN = 36,
        KAZAKHSTAN = 37,
        NORTH_KOREA = 38,
        PAKISTAN = 39,
        POLAND = 40,
        ROMANIA = 41,
        SAUDI_ARABIA = 42,
        SERBIA = 43,
        SLOVAKIA = 44,
        SOUTH_KOREA = 45,
        SWEDEN = 46,
        SYRIA = 47,
        YEMEN = 48,
        VIETNAM = 49,
        VENEZUELA = 50,
        TUNISIA = 51,
        THAILAND = 52,
        SUDAN = 53,
        PHILIPPINES = 54,
        MOROCCO = 55,
        MEXICO = 56,
        MALAYSIA = 57,
        LIBYA = 58,
        JORDAN = 59,
        INDONESIA = 60,
        HONDURAS = 61,
        ETHIOPIA = 62,
        CHILE = 63,
        BRAZIL = 64,
        BAHRAIN = 65,
        THIRDREICH = 66,
        YUGOSLAVIA = 67,
        USSR = 68,
        ITALIAN_SOCIAL_REPUBLIC = 69,
        ALGERIA = 70,
        KUWAIT = 71,
        QATAR = 72,
        OMAN = 73,
        UNITED_ARAB_EMIRATES = 74,
        SOUTH_AFRICA = 75,
        CUBA = 76,
        PORTUGAL = 77,
        GDR = 78,
        LEBANON = 79,
        CJTF_BLUE = 80,
        CJTF_RED = 81,
        UN_PEACEKEEPERS = 82,
        ARGENTINA = 83,
        CYPRUS = 84,
        SLOVENIA = 85,
        BOLIVIA = 86,
        GHANA = 87,
        NIGERIA = 88,
        PERU = 89,
        ECUADOR = 90,
        maxIndex = 91,
        AFGHANISTAN = 91,
        next_index = 92,
    }

    ---@enum country.id
    country.id = {
        RUSSIA = 0,
UKRAINE = 1,
USA = 2,
TURKEY = 3,
UK = 4,
FRANCE = 5,
GERMANY = 6,
AGGRESSORS = 7,
CANADA = 8,
SPAIN = 9,
THE_NETHERLANDS = 10,
BELGIUM = 11,
NORWAY = 12,
DENMARK = 13,
ISRAEL = 15,
GEORGIA = 16,
INSURGENTS = 17,
ABKHAZIA = 18,
SOUTH_OSETIA = 19,
ITALY = 20,
AUSTRALIA = 21,
SWITZERLAND = 22,
AUSTRIA = 23,
BELARUS = 24,
BULGARIA = 25,
CHEZH_REPUBLIC = 26,
CHINA = 27,
CROATIA = 28,
EGYPT = 29,
FINLAND = 30,
GREECE = 31,
HUNGARY = 32,
INDIA = 33,
IRAN = 34,
IRAQ = 35,
JAPAN = 36,
KAZAKHSTAN = 37,
NORTH_KOREA = 38,
PAKISTAN = 39,
POLAND = 40,
ROMANIA = 41,
SAUDI_ARABIA = 42,
SERBIA = 43,
SLOVAKIA = 44,
SOUTH_KOREA = 45,
SWEDEN = 46,
SYRIA = 47,
YEMEN = 48,
VIETNAM = 49,
VENEZUELA = 50,
TUNISIA = 51,
THAILAND = 52,
SUDAN = 53,
PHILIPPINES = 54,
MOROCCO = 55,
MEXICO = 56,
MALAYSIA = 57,
LIBYA = 58,
JORDAN = 59,
INDONESIA = 60,
HONDURAS = 61,
ETHIOPIA = 62,
CHILE = 63,
BRAZIL = 64,
BAHRAIN = 65,
THIRDREICH = 66,
YUGOSLAVIA = 67,
USSR = 68,
ITALIAN_SOCIAL_REPUBLIC = 69,
ALGERIA = 70,
KUWAIT = 71,
QATAR = 72,
OMAN = 73,
UNITED_ARAB_EMIRATES = 74,
SOUTH_AFRICA = 75,
CUBA = 76,
PORTUGAL = 77,
GDR = 78,
LEBANON = 79,
CJTF_BLUE = 80,
CJTF_RED = 81,
UN_PEACEKEEPERS = 82,
ARGENTINA = 83,
CYPRUS = 84,
SLOVENIA = 85,
BOLIVIA = 86,
GHANA = 87,
NIGERIA = 88,
PERU = 89,
ECUADOR = 90,
AFGHANISTAN = 91,
    }

    ---@enum country.name
    country.name = {
            [0] = "RUSSIA",
            [1] = "UKRAINE",
            [2] = "USA",
            [3] = "TURKEY",
            [4] = "UK",
            [5] = "FRANCE",
            [6] = "GERMANY",
            [7] = "AGGRESSORS",
            [8] = "CANADA",
            [9] = "SPAIN",
            [10] = "THE_NETHERLANDS",
            [11] = "BELGIUM",
            [12] = "NORWAY",
            [13] = "DENMARK",
            [15] = "ISRAEL",
            [16] = "GEORGIA",
            [17] = "INSURGENTS",
            [18] = "ABKHAZIA",
            [19] = "SOUTH_OSETIA",
            [20] = "ITALY",
            [21] = "AUSTRALIA",
            [22] = "SWITZERLAND",
            [23] = "AUSTRIA",
            [24] = "BELARUS",
            [25] = "BULGARIA",
            [26] = "CHEZH_REPUBLIC",
            [27] = "CHINA",
            [28] = "CROATIA",
            [29] = "EGYPT",
            [30] = "FINLAND",
            [31] = "GREECE",
            [32] = "HUNGARY",
            [33] = "INDIA",
            [34] = "IRAN",
            [35] = "IRAQ",
            [36] = "JAPAN",
            [37] = "KAZAKHSTAN",
            [38] = "NORTH_KOREA",
            [39] = "PAKISTAN",
            [40] = "POLAND",
            [41] = "ROMANIA",
            [42] = "SAUDI_ARABIA",
            [43] = "SERBIA",
            [44] = "SLOVAKIA",
            [45] = "SOUTH_KOREA",
            [46] = "SWEDEN",
            [47] = "SYRIA",
            [48] = "YEMEN",
            [49] = "VIETNAM",
            [50] = "VENEZUELA",
            [51] = "TUNISIA",
            [52] = "THAILAND",
            [53] = "SUDAN",
            [54] = "PHILIPPINES",
            [55] = "MOROCCO",
            [56] = "MEXICO",
            [57] = "MALAYSIA",
            [58] = "LIBYA",
            [59] = "JORDAN",
            [60] = "INDONESIA",
            [61] = "HONDURAS",
            [62] = "ETHIOPIA",
            [63] = "CHILE",
            [64] = "BRAZIL",
            [65] = "BAHRAIN",
            [66] = "THIRDREICH",
            [67] = "YUGOSLAVIA",
            [68] = "USSR",
            [69] = "ITALIAN_SOCIAL_REPUBLIC",
            [70] = "ALGERIA",
            [71] = "KUWAIT",
            [72] = "QATAR",
            [73] = "OMAN",
            [74] = "UNITED_ARAB_EMIRATES",
            [75] = "SOUTH_AFRICA",
            [76] = "CUBA",
            [77] = "PORTUGAL",
            [78] = "GDR",
            [79] = "LEBANON",
            [80] = "CJTF_BLUE",
            [81] = "CJTF_RED",
            [82] = "UN_PEACEKEEPERS",
            [83] = "ARGENTINA",
            [84] = "CYPRUS",
            [85] = "SLOVENIA",
            [86] = "BOLIVIA",
            [87] = "GHANA",
            [88] = "NIGERIA",
            [89] = "PERU",
            [90] = "ECUADOR",
            [91] = "AFGHANISTAN",
    }

    country.names = {
        [0] = "RUSSIA",
        [1] = "UKRAINE",
        [2] = "USA",
        [3] = "TURKEY",
        [4] = "UK",
        [5] = "FRANCE",
        [6] = "GERMANY",
        [7] = "AGGRESSORS",
        [8] = "CANADA",
        [9] = "SPAIN",
        [10] = "THE_NETHERLANDS",
        [11] = "BELGIUM",
        [12] = "NORWAY",
        [13] = "DENMARK",
        [15] = "ISRAEL",
        [16] = "GEORGIA",
        [17] = "INSURGENTS",
        [18] = "ABKHAZIA",
        [19] = "SOUTH_OSETIA",
        [20] = "ITALY",
        [21] = "AUSTRALIA",
        [22] = "SWITZERLAND",
        [23] = "AUSTRIA",
        [24] = "BELARUS",
        [25] = "BULGARIA",
        [26] = "CHEZH_REPUBLIC",
        [27] = "CHINA",
        [28] = "CROATIA",
        [29] = "EGYPT",
        [30] = "FINLAND",
        [31] = "GREECE",
        [32] = "HUNGARY",
        [33] = "INDIA",
        [34] = "IRAN",
        [35] = "IRAQ",
        [36] = "JAPAN",
        [37] = "KAZAKHSTAN",
        [38] = "NORTH_KOREA",
        [39] = "PAKISTAN",
        [40] = "POLAND",
        [41] = "ROMANIA",
        [42] = "SAUDI_ARABIA",
        [43] = "SERBIA",
        [44] = "SLOVAKIA",
        [45] = "SOUTH_KOREA",
        [46] = "SWEDEN",
        [47] = "SYRIA",
        [48] = "YEMEN",
        [49] = "VIETNAM",
        [50] = "VENEZUELA",
        [51] = "TUNISIA",
        [52] = "THAILAND",
        [53] = "SUDAN",
        [54] = "PHILIPPINES",
        [55] = "MOROCCO",
        [56] = "MEXICO",
        [57] = "MALAYSIA",
        [58] = "LIBYA",
        [59] = "JORDAN",
        [60] = "INDONESIA",
        [61] = "HONDURAS",
        [62] = "ETHIOPIA",
        [63] = "CHILE",
        [64] = "BRAZIL",
        [65] = "BAHRAIN",
        [66] = "THIRDREICH",
        [67] = "YUGOSLAVIA",
        [68] = "USSR",
        [69] = "ITALIAN_SOCIAL_REPUBLIC",
        [70] = "ALGERIA",
        [71] = "KUWAIT",
        [72] = "QATAR",
        [73] = "OMAN",
        [74] = "UNITED_ARAB_EMIRATES",
        [75] = "SOUTH_AFRICA",
        [76] = "CUBA",
        [77] = "PORTUGAL",
        [78] = "GDR",
        [79] = "LEBANON",
        [80] = "CJTF_BLUE",
        [81] = "CJTF_RED",
        [82] = "UN_PEACEKEEPERS",
        [83] = "ARGENTINA",
        [84] = "CYPRUS",
        [85] = "SLOVENIA",
        [86] = "BOLIVIA",
        [87] = "GHANA",
        [88] = "NIGERIA",
        [89] = "PERU",
        [90] = "ECUADOR",
        [91] = "AFGHANISTAN",
}








    --Functions
    do
        --No Docu
        function country.add() end

        --No Docu
        function country.get() end

        --No Docu
        function country.next() end
    end
end
