--[[
    Script by Tobias00723                          ████████
    from the TGFB server                      ████████  ████████
    Discord : https://discord.gg/hEHd4A3czx ██████          ██████
    any questions?                   ^^   ████     ▒      ▒     █████
    find me on my discord server     ^^ ████      ▒▒      ▒▒▒      ███
    _________________________________ ████       ▒▒▒      ▒▒▒       ███
                                      ███       ▒▒▒▒      ▒▒▒▒       ███
                                     ██       ▒▒▒▒        ▒▒▒▒▒      ███
                                    ███      ▒▒▒▒▒▒        ▒▒▒▒▒▒      ███
        Script as is.               ███     ▓▒▒▒▒▒▒        ▒▒▒▒▒▒▒     ███
                                    ███    ▒▒▒▒▒▒▒▒        ▓▒▒▒▒▒▒▓    ███
        Enjoy The open sauce!       ███   ▓▒▒▓▒▒▓▒▓         ▒▒▓▒▒▒▒▒   ███
                                    ███  ▓▒▓▓▒▓▓▒▓          ▓▓▒▓▓▓▓▓▓  ███
   If used credit, is appreaciated.  █  ▓▓▓▒▓ ▓▓▓▒          ▓▓▓▓ ▒▓▒▓▓  █
        Happy "borrowing" :)           ▓▓▓▓    ▓▓▓   ████    ▓▓▓   ▓▓▓▓
    _________________________________ ▓▓▓      ▓▓    ▓▓▓▓    ▓▓      ▓▓▓
                                     ▓▓        ▓▓    ▓▓▓▓    ▓▓        ▓▓
                                    ▓▓          ▓    ▓▓▓▓     ▓         ▓▓
    Copyright (c) 2025 TGFB                          ▓▓▓▓
    All rights reserved.                             ▓▓▓▓
]]


do
    ---@meta

    --classes
    do
        --vec 2
        do
            ---@class vec2
            ---@field x number
            ---@field y number
        end

        --- Vec3
        do
            ---@class vec3
            ---@field x number
            ---@field y number
            ---@field z number
        end

        --Position3
        do
            ---@class position3
            ---@field p vec3
            ---@field x vec3
            ---@field y vec3
            ---@field z vec3
        end

        --Forces names
        do
            ---@alias Force_name
            ---|'AirForce'
            ---|'AirBase'
            ---| string
        end

        --Attributes
        do
            ---TODO ignore "types" from script that generates this
            ---EXAMPLE : "Animal", "ADEquipment", "Effect", ... are invalid
            ---@alias Attributes
            ---|  "AircraftCarrier With Arresting Gear"
            ---|  "AircraftCarrier With Catapult"
            ---|  "Animal"
            ---|  "</WSTYPE>"
            ---|  "All"
            ---|  "AntiAir Armed Vehicles"
            ---|  "Armed Air Defence"
            ---|  "Armed Ship"
            ---|  "Armed ground units"
            ---|  "Armed ships"
            ---|  "Armed vehicles"
            ---|  "Armor"
            ---|  "Armored vehicles"
            ---|  "Arresting Gear"
            ---|  "Artillery"
            ---|  "Attack helicopters"
            ---|  "Aux"
            ---|  "Battle airplanes"
            ---|  "Battleplanes"
            ---|  "Bombers"
            ---|  "C-RAM"
            ---|  "Cargo"
            ---|  "Cargos"
            ---|  "Carriage"
            ---|  "Cars"
            ---|  "Corvettes"
            ---|  "Cruisers"
            ---|  "Datalink"
            ---|  "Destroyers"
            ---|  "DetectionByAWACS"
            ---|  "EWR"
            ---|  "Effect"
            ---|  "Fighters"
            ---|  "Fortification"
            ---|  "Fortifications"
            ---|  "Frigates"
            ---|  "GrassAirfield"
            ---|  "Ground Units"
            ---|  "Ground Units Non Airdefence"
            ---|  "Ground vehicles"
            ---|  "GroundObject"
            ---|  "Heavy armed ships"
            ---|  "HeavyArmoredUnits"
            ---|  "HelicopterCarrier"
            ---|  "Helicopters"
            ---|  "Heliport"
            ---|  "IFV"
            ---|  "AAA"
            ---|  "AA_flak"
            ---|  "AA_missile"
            ---|  "ACLS"
            ---|  "AD Auxillary Equipment"
            ---|  "ADEquipment"
            ---|  "AFAPD"
            ---|  "APC"
            ---|  "ATGM"
            ---|  "AWACS"
            ---|  "Air"
            ---|  "Air Defence"
            ---|  "Air Defence vehicles"
            ---|  "Aircraft Carriers"
            ---|  "AircraftCarrier"
            ---|  "AircraftCarrier With Tramplin"
            ---|  "IR Guided SAM"
            ---|  "Indirect fire"
            ---|  "Infantry"
            ---|  "Infantry carriers"
            ---|  "Interceptors"
            ---|  "JATO Container"
            ---|  "LR SAM"
            ---|  "Landing Ships"
            ---|  "Light armed ships"
            ---|  "LightArmoredUnits"
            ---|  "Link16"
            ---|  "Link4"
            ---|  "Locomotive"
            ---|  "MANPADS"
            ---|  "MANPADS AUX"
            ---|  "MLRS"
            ---|  "MR SAM"
            ---|  "Missile"
            ---|  "MissilesSS"
            ---|  "Mobile AAA"
            ---|  "Modern Tanks"
            ---|  "Multirole fighters"
            ---|  "NO_SAM"
            ---|  "Naval"
            ---|  "New infantry"
            ---|  "NonAndLightArmoredUnits"
            ---|  "NonArmoredUnits"
            ---|  "Old Tanks"
            ---|  "Personnel"
            ---|  "Planes"
            ---|  "Prone"
            ---|  "RADAR_BAND1_FOR_ARM"
            ---|  "RADAR_BAND2_FOR_ARM"
            ---|  "Refuelable"
            ---|  "Rocket Attack Valid AirDefence"
            ---|  "SAM"
            ---|  "SAM AUX"
            ---|  "SAM CC"
            ---|  "SAM LL"
            ---|  "SAM SR"
            ---|  "SAM TR"
            ---|  "SAM elements"
            ---|  "SAM related"
            ---|  "SR SAM"
            ---|  "SS_missile"
            ---|  "Ships"
            ---|  "Side approach departure"
            ---|  "Skeleton_type_A"
            ---|  "Static AAA"
            ---|  "Straight_in_approach_type"
            ---|  "Strategic bombers"
            ---|  "Submarines"
            ---|  "Tankers"
            ---|  "Tanks"
            ---|  "Train"
            ---|  "Transport helicopters"
            ---|  "Transports"
            ---|  "Trucks"
            ---|  "UAVs"
            ---|  "Unarmed"
            ---|  "Unarmed ships"
            ---|  "Unarmed vehicles"
            ---|  "Vehicles"
            ---|  "Warehouse"
            ---|  "bomb"
            ---|  "catapult"
            ---|  "human_vehicle"
            ---|  "low_reflection_vessel"
            ---|  "missile"
            ---|  "rocket"
            ---|  "shell"
            ---|  "ski_jump"
            ---|  "torpedo"
        end

        --Typenames
        do
            ---@alias TypeNames
            ---| TypeNames_AC
            ---| TypeNames_Heli
            ---| TypeNames_Ground
            ---| TypeNames_ship
            ---| TypeNames_Structures

            --AC
            do
                ---@alias TypeNames_AC
                ---|  "A-10A"
                ---|  "A-10C"
                ---|  "A-10C_2"
                ---|  "A-20G"
                ---|  "A-50"
                ---|  "AJS37"
                ---|  "An-26B"
                ---|  "An-30M"
                ---|  "AV8BNA"
                ---|  "B-1B"
                ---|  "B-52H"
                ---|  "Bf-109K-4"
                ---|  "C-101CC"
                ---|  "C-101EB"
                ---|  "C-130"
                ---|  "C-17A"
                ---|  "Christen Eagle II"
                ---|  "E-2C"
                ---|  "E-3A"
                ---|  "F-117A"
                ---|  "F-14A"
                ---|  "F-14A-135-GR"
                ---|  "F-14B"
                ---|  "F-15C"
                ---|  "F-15E"
                ---|  "F-15ESE"
                ---|  "F-16A"
                ---|  "F-16A MLU"
                ---|  "F-16C bl.50"
                ---|  "F-16C bl.52d"
                ---|  "F-16C_50"
                ---|  "F-4E"
                ---|  "F-4E-45MC"
                ---|  "F-5E"
                ---|  "F-5E-3"
                ---|  "F-5E-3_FC"
                ---|  "F-86F Sabre"
                ---|  "F-86F_FC"
                ---|  "F/A-18A"
                ---|  "F/A-18C"
                ---|  "F4U-1D"
                ---|  "F4U-1D_CW"
                ---|  "FA-18C_hornet"
                ---|  "Falcon_Gyrocopter"
                ---|  "FW-190A8"
                ---|  "FW-190D9"
                ---|  "H-6J"
                ---|  "Hawk"
                ---|  "I-16"
                ---|  "IL-76MD"
                ---|  "IL-78M"
                ---|  "J-11A"
                ---|  "JF-17"
                ---|  "KC-135"
                ---|  "KC130"
                ---|  "KC135MPRS"
                ---|  "KJ-2000"
                ---|  "L-39C"
                ---|  "L-39ZA"
                ---|  "M-2000C"
                ---|  "MB-339A"
                ---|  "MB-339APAN"
                ---|  "Mi-24P"
                ---|  "Mi-26"
                ---|  "Mi-8MT"
                ---|  "MiG-15bis"
                ---|  "MiG-15bis_FC"
                ---|  "MiG-19P"
                ---|  "MiG-21Bis"
                ---|  "MiG-23MLD"
                ---|  "MiG-25PD"
                ---|  "MiG-25RBT"
                ---|  "MiG-27K"
                ---|  "MiG-29A"
                ---|  "MiG-29G"
                ---|  "MiG-29S"
                ---|  "MiG-31"
                ---|  "Mirage 2000-5"
                ---|  "Mirage-F1AD"
                ---|  "Mirage-F1AZ"
                ---|  "Mirage-F1B"
                ---|  "Mirage-F1BD"
                ---|  "Mirage-F1BE"
                ---|  "Mirage-F1BQ"
                ---|  "Mirage-F1C"
                ---|  "Mirage-F1C-200"
                ---|  "Mirage-F1CE"
                ---|  "Mirage-F1CG"
                ---|  "Mirage-F1CH"
                ---|  "Mirage-F1CJ"
                ---|  "Mirage-F1CK"
                ---|  "Mirage-F1CR"
                ---|  "Mirage-F1CT"
                ---|  "Mirage-F1CZ"
                ---|  "Mirage-F1DDA"
                ---|  "Mirage-F1ED"
                ---|  "Mirage-F1EDA"
                ---|  "Mirage-F1EE"
                ---|  "Mirage-F1EH"
                ---|  "Mirage-F1EQ"
                ---|  "Mirage-F1JA"
                ---|  "Mirage-F1M-CE"
                ---|  "Mirage-F1M-EE"
                ---|  "MosquitoFBMkVI"
                ---|  "MQ-9 Reaper"
                ---|  "P-47D-30"
                ---|  "P-47D-30bl1"
                ---|  "P-47D-40"
                ---|  "P-51D"
                ---|  "P-51D-30-NA"
                ---|  "RQ-1A Predator"
                ---|  "S-3B"
                ---|  "S-3B Tanker"
                ---|  "SpitfireLFMkIX"
                ---|  "SpitfireLFMkIXCW"
                ---|  "Su-17M4"
                ---|  "Su-24M"
                ---|  "Su-24MR"
                ---|  "Su-25"
                ---|  "Su-25T"
                ---|  "Su-25TM"
                ---|  "Su-27"
                ---|  "Su-30"
                ---|  "Su-33"
                ---|  "Su-34"
                ---|  "TF-51D"
                ---|  "Tornado GR4"
                ---|  "Tornado IDS"
                ---|  "Tu-142"
                ---|  "Tu-160"
                ---|  "Tu-22M3"
                ---|  "Tu-95MS"
                ---|  "UH-1H"
                ---|  "WingLoong-I"
                ---|  "Yak-40"
                ---|  "Yak-52"
            end

            --Heli
            do
                ---@alias TypeNames_Heli
                ---|  "AH-1W"
                ---|  "AH-64A"
                ---|  "AH-64D"
                ---|  "AH-64D_BLK_II"
                ---|  "CH-47D"
                ---|  "CH-47Fbl1"
                ---|  "CH-53E"
                ---|  "Ka-27"
                ---|  "Ka-50"
                ---|  "Ka-50_3"
                ---|  "Mi-24P"
                ---|  "Mi-24V"
                ---|  "Mi-26"
                ---|  "Mi-28N"
                ---|  "Mi-8MT"
                ---|  "OH-58D"
                ---|  "OH58D"
                ---|  "SA342L"
                ---|  "SA342M"
                ---|  "SA342Minigun"
                ---|  "SA342Mistral"
                ---|  "SH-3W"
                ---|  "SH-60B"
                ---|  "UH-1H"
                ---|  "U
            end

            --Ground
            do
                ---@alias TypeNames_Ground
                ---|  "1L13 EWR"
                ---|  "2B11 mortar"
                ---|  "2S6 Tunguska"
                ---|  "55G6 EWR"
                ---|  "5p73 s-125 ln"
                ---|  "AA8"
                ---|  "AAV7"
                ---|  "ATMZ-5"
                ---|  "ATZ-10"
                ---|  "ATZ-5"
                ---|  "ATZ-60_Maz"
                ---|  "B600_drivable"
                ---|  "Bedford_MWD"
                ---|  "Blitz_36-6700A"
                ---|  "BMD-1"
                ---|  "BMP-1"
                ---|  "BMP-2"
                ---|  "BMP-3"
                ---|  "bofors40"
                ---|  "Boxcartrinity"
                ---|  "BRDM-2"
                ---|  "BTR-80"
                ---|  "BTR-82A"
                ---|  "BTR_D"
                ---|  "Bunker"
                ---|  "Challenger2"
                ---|  "CHAP_9K720_Cluster"
                ---|  "CHAP_9K720_HE"
                ---|  "CHAP_BMPT"
                ---|  "CHAP_FV101"
                ---|  "CHAP_FV107"
                ---|  "CHAP_IRISTSLM_CP"
                ---|  "CHAP_IRISTSLM_LN"
                ---|  "CHAP_IRISTSLM_STR"
                ---|  "CHAP_M1083"
                ---|  "CHAP_M1130"
                ---|  "CHAP_M142_ATACMS_M39A1"
                ---|  "CHAP_M142_ATACMS_M48"
                ---|  "CHAP_M142_GMLRS_M30"
                ---|  "CHAP_M142_GMLRS_M31"
                ---|  "CHAP_MATV"
                ---|  "CHAP_PantsirS1"
                ---|  "CHAP_T64BV"
                ---|  "CHAP_T84OplotM"
                ---|  "CHAP_T90M"
                ---|  "CHAP_TorM2"
                ---|  "CHAP_TOS1A"
                ---|  "Chieftain_mk3"
                ---|  "Coach a passenger"
                ---|  "Coach a platform"
                ---|  "Coach a tank blue"
                ---|  "Coach a tank yellow"
                ---|  "Coach cargo"
                ---|  "Coach cargo open"
                ---|  "Cobra"
                ---|  "Dog Ear radar"
                ---|  "Electric locomotive"
                ---|  "ES44AH"
                ---|  "flak18"
                ---|  "FPS-117"
                ---|  "FPS-117 Dome"
                ---|  "FPS-117 ECS"
                ---|  "GAZ-3307"
                ---|  "GAZ-3308"
                ---|  "GAZ-66"
                ---|  "GD-20"
                ---|  "generator_5i57"
                ---|  "Gepard"
                ---|  "Grad-URAL"
                ---|  "Grad_FDDM"
                ---|  "Hawk cwar"
                ---|  "Hawk ln"
                ---|  "Hawk pcp"
                ---|  "Hawk sr"
                ---|  "Hawk tr"
                ---|  "HEMTT TFFT"
                ---|  "HEMTT_C-RAM_Phalanx"
                ---|  "HL_B8M1"
                ---|  "HL_DSHK"
                ---|  "HL_KORD"
                ---|  "HL_ZU-23"
                ---|  "house1arm"
                ---|  "house2arm"
                ---|  "houseA_arm"
                ---|  "HQ-7_LN_P"
                ---|  "HQ-7_LN_SP"
                ---|  "HQ-7_STR_SP"
                ---|  "Hummer"
                ---|  "hy_launcher"
                ---|  "Igla manpad INS"
                ---|  "IKARUS Bus"
                ---|  "Infantry AK"
                ---|  "Infantry AK Ins"
                ---|  "Infantry AK ver2"
                ---|  "Infantry AK ver3"
                ---|  "JTAC"
                ---|  "KAMAZ Truck"
                ---|  "KrAZ6322"
                ---|  "KS-19"
                ---|  "Kub 1S91 str"
                ---|  "Kub 2P25 ln"
                ---|  "L118_Unit"
                ---|  "Land_Rover_101_FC"
                ---|  "Land_Rover_109_S3"
                ---|  "LARC-V"
                ---|  "LAV-25"
                ---|  "LAZ Bus"
                ---|  "Leclerc"
                ---|  "Leopard-2"
                ---|  "leopard-2A4"
                ---|  "leopard-2A4_trs"
                ---|  "Leopard-2A5"
                ---|  "Leopard1A3"
                ---|  "LiAZ Bus"
                ---|  "Locomotive"
                ---|  "M 818"
                ---|  "M-1 Abrams"
                ---|  "M-109"
                ---|  "M-113"
                ---|  "M-2 Bradley"
                ---|  "M-60"
                ---|  "M1043 HMMWV Armament"
                ---|  "M1045 HMMWV TOW"
                ---|  "M1097 Avenger"
                ---|  "M1126 Stryker ICV"
                ---|  "M1128 Stryker MGS"
                ---|  "M1134 Stryker ATGM"
                ---|  "M1A2C_SEP_V3"
                ---|  "M2A1_halftrack"
                ---|  "M48 Chaparral"
                ---|  "M4_Sherman"
                ---|  "M6 Linebacker"
                ---|  "M978 HEMTT Tanker"
                ---|  "Marder"
                ---|  "MaxxPro_MRAP"
                ---|  "MAZ-6303"
                ---|  "MCV-80"
                ---|  "Merkava_Mk4"
                ---|  "MJ-1_drivable"
                ---|  "MLRS"
                ---|  "MLRS FDDM"
                ---|  "MTLB"
                ---|  "NASAMS_Command_Post"
                ---|  "NASAMS_LN_B"
                ---|  "NASAMS_LN_C"
                ---|  "NASAMS_Radar_MPQ64F1"
                ---|  "Osa 9A33 ln"
                ---|  "outpost"
                ---|  "outpost_road"
                ---|  "outpost_road_l"
                ---|  "outpost_road_r"
                ---|  "p-19 s-125 sr"
                ---|  "P20_drivable"
                ---|  "Paratrooper AKS-74"
                ---|  "Paratrooper RPG-16"
                ---|  "Patriot AMG"
                ---|  "Patriot cp"
                ---|  "Patriot ECS"
                ---|  "Patriot EPP"
                ---|  "Patriot ln"
                ---|  "Patriot str"
                ---|  "PLZ05"
                ---|  "Predator GCS"
                ---|  "Predator TrojanSpirit"
                ---|  "PT_76"
                ---|  "Pz_IV_H"
                ---|  "r11_volvo_drivable"
                ---|  "rapier_fsa_blindfire_radar"
                ---|  "rapier_fsa_launcher"
                ---|  "rapier_fsa_optical_tracker_unit"
                ---|  "RD_75"
                ---|  "RLS_19J6"
                ---|  "Roland ADS"
                ---|  "Roland Radar"
                ---|  "RPC_5N62V"
                ---|  "S-200_Launcher"
                ---|  "S-300PS 40B6M tr"
                ---|  "S-300PS 40B6MD sr"
                ---|  "S-300PS 40B6MD sr_19J6"
                ---|  "S-300PS 54K6 cp"
                ---|  "S-300PS 5H63C 30H6_tr"
                ---|  "S-300PS 5P85C ln"
                ---|  "S-300PS 5P85D ln"
                ---|  "S-300PS 64H6E sr"
                ---|  "S-60_Type59_Artillery"
                ---|  "S_75_ZIL"
                ---|  "S_75M_Volhov"
                ---|  "SA-11 Buk CC 9S470M1"
                ---|  "SA-11 Buk LN 9A310M1"
                ---|  "SA-11 Buk SR 9S18M1"
                ---|  "SA-18 Igla comm"
                ---|  "SA-18 Igla manpad"
                ---|  "SA-18 Igla-S comm"
                ---|  "SA-18 Igla-S manpad"
                ---|  "Sandbox"
                ---|  "SAU 2-C9"
                ---|  "SAU Akatsia"
                ---|  "SAU Gvozdika"
                ---|  "SAU Msta"
                ---|  "Scud_B"
                ---|  "Sd_Kfz_251"
                ---|  "Silkworm_SR"
                ---|  "SKP-11"
                ---|  "Smerch"
                ---|  "Smerch_HE"
                ---|  "snr s-125 tr"
                ---|  "SNR_75V"
                ---|  "Soldier AK"
                ---|  "Soldier M249"
                ---|  "Soldier M4"
                ---|  "Soldier M4 GRG"
                ---|  "Soldier RPG"
                ---|  "Soldier stinger"
                ---|  "SON_9"
                ---|  "SpGH_Dana"
                ---|  "Stinger comm"
                ---|  "Stinger comm dsr"
                ---|  "Strela-1 9P31"
                ---|  "Strela-10M3"
                ---|  "Suidae"
                ---|  "T-55"
                ---|  "T-72B"
                ---|  "T-72B3"
                ---|  "T-80UD"
                ---|  "T-90"
                ---|  "T155_Firtina"
                ---|  "TACAN_beacon"
                ---|  "tacr2a"
                ---|  "Tankcartrinity"
                ---|  "Tigr_233036"
                ---|  "Tor 9A331"
                ---|  "TPZ"
                ---|  "Trolley bus"
                ---|  "tt_B8M1"
                ---|  "tt_DSHK"
                ---|  "tt_KORD"
                ---|  "tt_ZU-23"
                ---|  "TugHarlan_drivable"
                ---|  "TYPE-59"
                ---|  "Type_3_80mm_AA"
                ---|  "Type_88_75mm_AA"
                ---|  "Type_89_I_Go"
                ---|  "Type_94_25mm_AA_Truck"
                ---|  "Type_94_Truck"
                ---|  "Type_96_25mm_AA"
                ---|  "Type_98_Ke_Ni"
                ---|  "Type_98_So_Da"
                ---|  "TZ-22_KrAZ"
                ---|  "UAZ-469"
                ---|  "Uragan_BM-27"
                ---|  "Ural ATsP-6"
                ---|  "Ural-375"
                ---|  "Ural-375 PBU"
                ---|  "Ural-375 ZU-23"
                ---|  "Ural-375 ZU-23 Insurgent"
                ---|  "Ural-4320 APA-5D"
                ---|  "Ural-4320-31"
                ---|  "Ural-4320T"
                ---|  "VAB_Mephisto"
                ---|  "VAZ Car"
                ---|  "Vulcan"
                ---|  "Wellcarnsc"
                ---|  "ZBD04A"
                ---|  "ZiL-131 APA-80"
                ---|  "ZIL-131 KUNG"
                ---|  "ZIL-135"
                ---|  "ZIL-4331"
                ---|  "ZSU-23-4 Shilka"
                ---|  "ZSU_57_2"
                ---|  "ZTZ96B"
                ---|  "ZU-23 Closed Insurgent"
                ---|  "ZU-23 Emplacement"
                ---|  "ZU-23 Emplacement Closed"
                ---|  "ZU-23 Insurgent"
            end

            --Ship
            do
                ---@alias TypeNames_ship
                ---|  "ALBATROS"
                ---|  "ara_vdm"
                ---|  "atconveyor"
                ---|  "BDK-775"
                ---|  "CastleClass_01"
                ---|  "CHAP_Project22160"
                ---|  "CHAP_Project22160_TorM2KM"
                ---|  "CV_1143_5"
                ---|  "CVN_71"
                ---|  "CVN_72"
                ---|  "CVN_73"
                ---|  "CVN_75"
                ---|  "Dry-cargo ship-1"
                ---|  "Dry-cargo ship-2"
                ---|  "ELNYA"
                ---|  "Essex"
                ---|  "Forrestal"
                ---|  "HandyWind"
                ---|  "HarborTug"
                ---|  "hms_invincible"
                ---|  "IMPROVED_KILO"
                ---|  "KILO"
                ---|  "KUZNECOW"
                ---|  "La_Combattante_II"
                ---|  "leander-gun-achilles"
                ---|  "leander-gun-andromeda"
                ---|  "leander-gun-ariadne"
                ---|  "leander-gun-condell"
                ---|  "leander-gun-lynch"
                ---|  "LHA_Tarawa"
                ---|  "MOLNIYA"
                ---|  "MOSCOW"
                ---|  "NEUSTRASH"
                ---|  "PERRY"
                ---|  "PIOTR"
                ---|  "REZKY"
                ---|  "santafe"
                ---|  "Seawise_Giant"
                ---|  "Ship_Tilde_Supply"
                ---|  "SOM"
                ---|  "speedboat"
                ---|  "Stennis"
                ---|  "TICONDEROG"
                ---|  "Type_052B"
                ---|  "Type_052C"
                ---|  "Type_054A"
                ---|  "Type_071"
                ---|  "Type_093"
                ---|  "USS_Arleigh_Burke_IIa"
                ---|  "VINSON"
                ---|  "ZWEZDNY"
            end

            --Structures
            do
                ---@alias TypeNames_Structures
                ---| string
            end
        end
    end

    ED_FINAL_VERSION    = true ---@type boolean
    ED_PUBLIC_AVAILABLE = true ---@type boolean
    _APP_VERSION        = "2.9.21.16362" ---@type string
    db_path             = "./Scripts/Database/" ---@type string
    troopsPath          = "./Scripts/Database/troops/" ---@type string


    --Functions
    do
        --No Docu
        function class() end

        --No Docu
        function doZipFile() end

        --No Docu
        -- garbage collecting info
        function gcinfo() end

        --No Docu
        function merge_all_units_to_AGGRESSORS() end

        --No Docu
        function safe_require() end
    end
end
